-- MLBPredicts canonical PostgreSQL schema (Supabase primary).
-- This file is Postgres-only by design. For local sqlite fallback, use schema_sqlite.sql.

-- ============================================================
-- REFERENCE TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS stadiums (
    stadium_id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    team_abbr TEXT NOT NULL UNIQUE,
    city TEXT,
    state TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    elevation_ft INTEGER,
    roof_type TEXT CHECK(roof_type IN ('open', 'retractable', 'dome')),
    lf_distance INTEGER,
    cf_distance INTEGER,
    rf_distance INTEGER,
    hr_park_factor DOUBLE PRECISION DEFAULT 1.0
);

CREATE TABLE IF NOT EXISTS park_factors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stadium_id BIGINT REFERENCES stadiums(stadium_id),
    season INTEGER NOT NULL,
    hr_factor DOUBLE PRECISION NOT NULL,
    hr_factor_lhb DOUBLE PRECISION,
    hr_factor_rhb DOUBLE PRECISION,
    UNIQUE(stadium_id, season)
);

CREATE TABLE IF NOT EXISTS umpires (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    umpire_name TEXT NOT NULL,
    season INTEGER NOT NULL,
    games_umped INTEGER,
    avg_runs_per_game DOUBLE PRECISION,
    k_pct_above_avg DOUBLE PRECISION,
    zone_size TEXT,
    hr_per_game_avg DOUBLE PRECISION,
    UNIQUE(umpire_name, season)
);

-- ============================================================
-- DAILY GAME TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS games (
    game_id BIGINT PRIMARY KEY,
    game_date DATE NOT NULL,
    game_time TEXT,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    stadium_id BIGINT REFERENCES stadiums(stadium_id),
    home_pitcher_id BIGINT,
    away_pitcher_id BIGINT,
    home_pitcher_name TEXT,
    away_pitcher_name TEXT,
    home_pitcher_hand TEXT CHECK(home_pitcher_hand IN ('L', 'R')),
    away_pitcher_hand TEXT CHECK(away_pitcher_hand IN ('L', 'R')),
    umpire_name TEXT,
    status TEXT DEFAULT 'scheduled',
    home_score INTEGER,
    away_score INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_games_date ON games(game_date);
CREATE INDEX IF NOT EXISTS idx_games_teams ON games(home_team, away_team);

CREATE TABLE IF NOT EXISTS weather (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT REFERENCES games(game_id),
    fetch_time TIMESTAMPTZ NOT NULL,
    temperature_f DOUBLE PRECISION,
    humidity_pct DOUBLE PRECISION,
    wind_speed_mph DOUBLE PRECISION,
    wind_direction_deg INTEGER,
    wind_description TEXT,
    wind_hr_impact DOUBLE PRECISION,
    precipitation_pct DOUBLE PRECISION,
    conditions TEXT,
    UNIQUE(game_id, fetch_time)
);

CREATE INDEX IF NOT EXISTS idx_weather_game ON weather(game_id);

CREATE TABLE IF NOT EXISTS lineups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    game_id BIGINT NOT NULL REFERENCES games(game_id),
    team_id TEXT NOT NULL,
    player_id BIGINT NOT NULL,
    batting_order INTEGER,
    position TEXT,
    is_starter SMALLINT NOT NULL DEFAULT 0 CHECK(is_starter IN (0, 1)),
    confirmed SMALLINT NOT NULL DEFAULT 0 CHECK(confirmed IN (0, 1)),
    source TEXT NOT NULL DEFAULT 'mlb_stats_api',
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    active_version SMALLINT NOT NULL DEFAULT 1 CHECK(active_version IN (0, 1)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(
        game_date,
        game_id,
        team_id,
        player_id,
        batting_order,
        position,
        is_starter,
        confirmed,
        fetched_at
    )
);

CREATE INDEX IF NOT EXISTS idx_lineups_game_date ON lineups(game_date);
CREATE INDEX IF NOT EXISTS idx_lineups_game_id ON lineups(game_id);
CREATE INDEX IF NOT EXISTS idx_lineups_team_id ON lineups(team_id);
CREATE INDEX IF NOT EXISTS idx_lineups_player_id ON lineups(player_id);
CREATE INDEX IF NOT EXISTS idx_lineups_fetched_at ON lineups(fetched_at);
CREATE INDEX IF NOT EXISTS idx_lineups_active_version ON lineups(active_version);

CREATE TABLE IF NOT EXISTS umpire_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    game_id BIGINT NOT NULL,
    umpire_name TEXT NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    source TEXT NOT NULL DEFAULT 'mlb_stats_api',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, game_id, umpire_name, fetched_at)
);

CREATE INDEX IF NOT EXISTS idx_umpire_assignments_date ON umpire_assignments(game_date);
CREATE INDEX IF NOT EXISTS idx_umpire_assignments_game ON umpire_assignments(game_id);
CREATE INDEX IF NOT EXISTS idx_umpire_assignments_fetched_at ON umpire_assignments(fetched_at);

-- ============================================================
-- RAW STATS TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS batter_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    player_name TEXT NOT NULL,
    team TEXT,
    bat_hand TEXT CHECK(bat_hand IN ('L', 'R', 'S')),
    stat_date DATE NOT NULL,
    window_days INTEGER NOT NULL,
    barrel_pct DOUBLE PRECISION,
    hard_hit_pct DOUBLE PRECISION,
    avg_exit_velo DOUBLE PRECISION,
    max_exit_velo DOUBLE PRECISION,
    fly_ball_pct DOUBLE PRECISION,
    hr_per_fb DOUBLE PRECISION,
    pull_pct DOUBLE PRECISION,
    avg_launch_angle DOUBLE PRECISION,
    sweet_spot_pct DOUBLE PRECISION,
    iso_power DOUBLE PRECISION,
    slg DOUBLE PRECISION,
    woba DOUBLE PRECISION,
    xwoba DOUBLE PRECISION,
    xslg DOUBLE PRECISION,
    pa INTEGER,
    ab INTEGER,
    hrs INTEGER,
    k_pct DOUBLE PRECISION,
    bb_pct DOUBLE PRECISION,
    iso_vs_lhp DOUBLE PRECISION,
    iso_vs_rhp DOUBLE PRECISION,
    barrel_pct_vs_lhp DOUBLE PRECISION,
    barrel_pct_vs_rhp DOUBLE PRECISION,
    hr_count_vs_lhp INTEGER,
    hr_count_vs_rhp INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, stat_date, window_days)
);

CREATE INDEX IF NOT EXISTS idx_batter_stats_player ON batter_stats(player_id, stat_date);
CREATE INDEX IF NOT EXISTS idx_batter_stats_date ON batter_stats(stat_date);

CREATE TABLE IF NOT EXISTS pitcher_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    player_name TEXT NOT NULL,
    team TEXT,
    pitch_hand TEXT CHECK(pitch_hand IN ('L', 'R')),
    stat_date DATE NOT NULL,
    window_days INTEGER NOT NULL,
    batters_faced INTEGER,
    k_pct DOUBLE PRECISION,
    bb_pct DOUBLE PRECISION,
    so_per_9 DOUBLE PRECISION,
    hr_per_9 DOUBLE PRECISION,
    hr_per_fb DOUBLE PRECISION,
    fly_ball_pct DOUBLE PRECISION,
    hard_hit_pct_against DOUBLE PRECISION,
    barrel_pct_against DOUBLE PRECISION,
    avg_exit_velo_against DOUBLE PRECISION,
    avg_fastball_velo DOUBLE PRECISION,
    fastball_velo_trend DOUBLE PRECISION,
    whiff_pct DOUBLE PRECISION,
    chase_pct DOUBLE PRECISION,
    zone_pct DOUBLE PRECISION,
    innings_pitched DOUBLE PRECISION,
    pitches_per_start DOUBLE PRECISION,
    days_rest INTEGER,
    era DOUBLE PRECISION,
    fip DOUBLE PRECISION,
    xfip DOUBLE PRECISION,
    xera DOUBLE PRECISION,
    hr_per_9_vs_lhb DOUBLE PRECISION,
    hr_per_9_vs_rhb DOUBLE PRECISION,
    iso_allowed_vs_lhb DOUBLE PRECISION,
    iso_allowed_vs_rhb DOUBLE PRECISION,
    k_pct_vs_lhb DOUBLE PRECISION,
    k_pct_vs_rhb DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, stat_date, window_days)
);

CREATE INDEX IF NOT EXISTS idx_pitcher_stats_player ON pitcher_stats(player_id, stat_date);
CREATE INDEX IF NOT EXISTS idx_pitcher_stats_date ON pitcher_stats(stat_date);

-- ============================================================
-- FEATURE STORE TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS batter_daily_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    player_id BIGINT NOT NULL,
    team_id TEXT,
    bats TEXT,
    pa_7 INTEGER,
    pa_14 INTEGER,
    pa_30 INTEGER,
    k_pct_7 DOUBLE PRECISION,
    k_pct_14 DOUBLE PRECISION,
    k_pct_30 DOUBLE PRECISION,
    bb_pct_7 DOUBLE PRECISION,
    bb_pct_14 DOUBLE PRECISION,
    bb_pct_30 DOUBLE PRECISION,
    barrel_pct_7 DOUBLE PRECISION,
    barrel_pct_14 DOUBLE PRECISION,
    barrel_pct_30 DOUBLE PRECISION,
    hard_hit_pct_7 DOUBLE PRECISION,
    hard_hit_pct_14 DOUBLE PRECISION,
    hard_hit_pct_30 DOUBLE PRECISION,
    avg_exit_velo_7 DOUBLE PRECISION,
    avg_exit_velo_14 DOUBLE PRECISION,
    avg_exit_velo_30 DOUBLE PRECISION,
    fly_ball_pct_7 DOUBLE PRECISION,
    fly_ball_pct_14 DOUBLE PRECISION,
    fly_ball_pct_30 DOUBLE PRECISION,
    line_drive_pct_7 DOUBLE PRECISION,
    line_drive_pct_14 DOUBLE PRECISION,
    line_drive_pct_30 DOUBLE PRECISION,
    gb_pct_7 DOUBLE PRECISION,
    gb_pct_14 DOUBLE PRECISION,
    gb_pct_30 DOUBLE PRECISION,
    pull_pct_7 DOUBLE PRECISION,
    pull_pct_14 DOUBLE PRECISION,
    pull_pct_30 DOUBLE PRECISION,
    sweet_spot_pct_7 DOUBLE PRECISION,
    sweet_spot_pct_14 DOUBLE PRECISION,
    sweet_spot_pct_30 DOUBLE PRECISION,
    avg_launch_angle_7 DOUBLE PRECISION,
    avg_launch_angle_14 DOUBLE PRECISION,
    avg_launch_angle_30 DOUBLE PRECISION,
    iso_7 DOUBLE PRECISION,
    iso_14 DOUBLE PRECISION,
    iso_30 DOUBLE PRECISION,
    slg_7 DOUBLE PRECISION,
    slg_14 DOUBLE PRECISION,
    slg_30 DOUBLE PRECISION,
    ba_7 DOUBLE PRECISION,
    ba_14 DOUBLE PRECISION,
    ba_30 DOUBLE PRECISION,
    hit_rate_7 DOUBLE PRECISION,
    hit_rate_14 DOUBLE PRECISION,
    hit_rate_30 DOUBLE PRECISION,
    tb_per_pa_7 DOUBLE PRECISION,
    tb_per_pa_14 DOUBLE PRECISION,
    tb_per_pa_30 DOUBLE PRECISION,
    hr_rate_7 DOUBLE PRECISION,
    hr_rate_14 DOUBLE PRECISION,
    hr_rate_30 DOUBLE PRECISION,
    singles_rate_14 DOUBLE PRECISION,
    singles_rate_30 DOUBLE PRECISION,
    doubles_rate_14 DOUBLE PRECISION,
    doubles_rate_30 DOUBLE PRECISION,
    triples_rate_14 DOUBLE PRECISION,
    triples_rate_30 DOUBLE PRECISION,
    rbi_rate_14 DOUBLE PRECISION,
    rbi_rate_30 DOUBLE PRECISION,
    runs_rate_14 DOUBLE PRECISION,
    runs_rate_30 DOUBLE PRECISION,
    walk_rate_14 DOUBLE PRECISION,
    walk_rate_30 DOUBLE PRECISION,
    iso_vs_lhp DOUBLE PRECISION,
    iso_vs_rhp DOUBLE PRECISION,
    hit_rate_vs_lhp DOUBLE PRECISION,
    hit_rate_vs_rhp DOUBLE PRECISION,
    k_pct_vs_lhp DOUBLE PRECISION,
    k_pct_vs_rhp DOUBLE PRECISION,
    hot_cold_delta_iso DOUBLE PRECISION,
    hot_cold_delta_hit_rate DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, player_id)
);

CREATE INDEX IF NOT EXISTS idx_batter_daily_features_game_date ON batter_daily_features(game_date);
CREATE INDEX IF NOT EXISTS idx_batter_daily_features_player_id ON batter_daily_features(player_id);
CREATE INDEX IF NOT EXISTS idx_batter_daily_features_team_id ON batter_daily_features(team_id);

CREATE TABLE IF NOT EXISTS pitcher_daily_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    pitcher_id BIGINT NOT NULL,
    team_id TEXT,
    throws TEXT,
    batters_faced_14 INTEGER,
    batters_faced_30 INTEGER,
    k_pct_14 DOUBLE PRECISION,
    k_pct_30 DOUBLE PRECISION,
    bb_pct_14 DOUBLE PRECISION,
    bb_pct_30 DOUBLE PRECISION,
    hr_per_9_14 DOUBLE PRECISION,
    hr_per_9_30 DOUBLE PRECISION,
    hr_per_fb_14 DOUBLE PRECISION,
    hr_per_fb_30 DOUBLE PRECISION,
    hard_hit_pct_allowed_14 DOUBLE PRECISION,
    hard_hit_pct_allowed_30 DOUBLE PRECISION,
    barrel_pct_allowed_14 DOUBLE PRECISION,
    barrel_pct_allowed_30 DOUBLE PRECISION,
    avg_exit_velo_allowed_14 DOUBLE PRECISION,
    avg_exit_velo_allowed_30 DOUBLE PRECISION,
    fly_ball_pct_allowed_14 DOUBLE PRECISION,
    fly_ball_pct_allowed_30 DOUBLE PRECISION,
    whiff_pct_14 DOUBLE PRECISION,
    whiff_pct_30 DOUBLE PRECISION,
    chase_pct_14 DOUBLE PRECISION,
    chase_pct_30 DOUBLE PRECISION,
    avg_fastball_velo_14 DOUBLE PRECISION,
    avg_fastball_velo_30 DOUBLE PRECISION,
    fastball_velo_trend_14 DOUBLE PRECISION,
    outs_recorded_avg_last_5 DOUBLE PRECISION,
    pitches_avg_last_5 DOUBLE PRECISION,
    starter_role_confidence DOUBLE PRECISION,
    split_k_pct_vs_lhh DOUBLE PRECISION,
    split_k_pct_vs_rhh DOUBLE PRECISION,
    split_hr_allowed_rate_vs_lhh DOUBLE PRECISION,
    split_hr_allowed_rate_vs_rhh DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, pitcher_id)
);

CREATE INDEX IF NOT EXISTS idx_pitcher_daily_features_game_date ON pitcher_daily_features(game_date);
CREATE INDEX IF NOT EXISTS idx_pitcher_daily_features_pitcher_id ON pitcher_daily_features(pitcher_id);
CREATE INDEX IF NOT EXISTS idx_pitcher_daily_features_team_id ON pitcher_daily_features(team_id);

CREATE TABLE IF NOT EXISTS team_daily_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    team_id TEXT NOT NULL,
    opponent_team_id TEXT,
    offense_k_pct_14 DOUBLE PRECISION,
    offense_k_pct_30 DOUBLE PRECISION,
    offense_bb_pct_14 DOUBLE PRECISION,
    offense_bb_pct_30 DOUBLE PRECISION,
    offense_iso_14 DOUBLE PRECISION,
    offense_iso_30 DOUBLE PRECISION,
    offense_ba_14 DOUBLE PRECISION,
    offense_ba_30 DOUBLE PRECISION,
    offense_obp_14 DOUBLE PRECISION,
    offense_obp_30 DOUBLE PRECISION,
    offense_slg_14 DOUBLE PRECISION,
    offense_slg_30 DOUBLE PRECISION,
    offense_hit_rate_14 DOUBLE PRECISION,
    offense_hit_rate_30 DOUBLE PRECISION,
    offense_tb_per_pa_14 DOUBLE PRECISION,
    offense_tb_per_pa_30 DOUBLE PRECISION,
    runs_per_game_14 DOUBLE PRECISION,
    runs_per_game_30 DOUBLE PRECISION,
    hr_rate_14 DOUBLE PRECISION,
    hr_rate_30 DOUBLE PRECISION,
    bullpen_era_proxy_14 DOUBLE PRECISION,
    bullpen_whip_proxy_14 DOUBLE PRECISION,
    bullpen_k_pct_14 DOUBLE PRECISION,
    bullpen_hr9_14 DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, team_id)
);

CREATE INDEX IF NOT EXISTS idx_team_daily_features_game_date ON team_daily_features(game_date);
CREATE INDEX IF NOT EXISTS idx_team_daily_features_team_id ON team_daily_features(team_id);
CREATE INDEX IF NOT EXISTS idx_team_daily_features_opp_team_id ON team_daily_features(opponent_team_id);

CREATE TABLE IF NOT EXISTS game_context_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    game_id BIGINT NOT NULL REFERENCES games(game_id),
    home_team_id TEXT NOT NULL,
    away_team_id TEXT NOT NULL,
    home_pitcher_id BIGINT,
    away_pitcher_id BIGINT,
    park_factor_hr DOUBLE PRECISION,
    park_factor_runs DOUBLE PRECISION,
    park_factor_hits DOUBLE PRECISION,
    weather_temp_f DOUBLE PRECISION,
    weather_wind_speed_mph DOUBLE PRECISION,
    weather_wind_dir TEXT,
    weather_hr_multiplier DOUBLE PRECISION,
    weather_run_multiplier DOUBLE PRECISION,
    umpire_name TEXT,
    umpire_k_boost DOUBLE PRECISION,
    umpire_run_env DOUBLE PRECISION,
    lineups_confirmed_home SMALLINT NOT NULL DEFAULT 0 CHECK(lineups_confirmed_home IN (0, 1)),
    lineups_confirmed_away SMALLINT NOT NULL DEFAULT 0 CHECK(lineups_confirmed_away IN (0, 1)),
    is_final_context SMALLINT NOT NULL DEFAULT 0 CHECK(is_final_context IN (0, 1)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, game_id)
);

CREATE INDEX IF NOT EXISTS idx_game_context_features_game_date ON game_context_features(game_date);
CREATE INDEX IF NOT EXISTS idx_game_context_features_game_id ON game_context_features(game_id);
CREATE INDEX IF NOT EXISTS idx_game_context_features_home_team ON game_context_features(home_team_id);
CREATE INDEX IF NOT EXISTS idx_game_context_features_away_team ON game_context_features(away_team_id);

-- ============================================================
-- ODDS / SCORES / OUTCOMES / BETS
-- ============================================================

CREATE TABLE IF NOT EXISTS hr_odds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT REFERENCES games(game_id),
    game_date DATE NOT NULL,
    player_id BIGINT NOT NULL,
    player_name TEXT NOT NULL,
    sportsbook TEXT NOT NULL,
    market TEXT DEFAULT 'hr',
    over_price INTEGER,
    under_price INTEGER,
    implied_prob_over DOUBLE PRECISION,
    implied_prob_under DOUBLE PRECISION,
    fetch_time TIMESTAMPTZ NOT NULL,
    UNIQUE(game_id, player_id, sportsbook, fetch_time)
);

CREATE INDEX IF NOT EXISTS idx_hr_odds_game ON hr_odds(game_date, player_id);

CREATE TABLE IF NOT EXISTS score_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_type TEXT NOT NULL CHECK(run_type IN (
        'overnight_features',
        'morning_context',
        'odds_refresh',
        'lineup_rescore',
        'manual_score',
        'backtest',
        'manual_features'
    )),
    game_date DATE,
    market TEXT,
    triggered_by TEXT NOT NULL DEFAULT 'system',
    status TEXT NOT NULL DEFAULT 'started',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    rows_scored INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_score_runs_date_market ON score_runs(game_date, market);
CREATE INDEX IF NOT EXISTS idx_score_runs_type_status ON score_runs(run_type, status);
CREATE INDEX IF NOT EXISTS idx_score_runs_started_at ON score_runs(started_at);

CREATE TABLE IF NOT EXISTS hr_model_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT REFERENCES games(game_id),
    game_date DATE NOT NULL,
    player_id BIGINT NOT NULL,
    player_name TEXT NOT NULL,
    team TEXT,
    opponent TEXT,
    opposing_pitcher TEXT,
    barrel_score DOUBLE PRECISION,
    matchup_score DOUBLE PRECISION,
    park_weather_score DOUBLE PRECISION,
    pitcher_vuln_score DOUBLE PRECISION,
    hot_cold_score DOUBLE PRECISION,
    model_score DOUBLE PRECISION,
    model_prob DOUBLE PRECISION,
    book_implied_prob DOUBLE PRECISION,
    edge DOUBLE PRECISION,
    signal TEXT CHECK(signal IN ('BET', 'LEAN', 'SKIP', 'FADE')),
    confidence TEXT CHECK(confidence IN ('HIGH', 'MEDIUM', 'LOW')),
    propfinder_signal TEXT,
    ballparkpal_signal TEXT,
    hrpredict_signal TEXT,
    consensus_agreement INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(game_id, player_id, game_date)
);

CREATE INDEX IF NOT EXISTS idx_model_scores_date ON hr_model_scores(game_date);
CREATE INDEX IF NOT EXISTS idx_model_scores_signal ON hr_model_scores(signal);

CREATE TABLE IF NOT EXISTS market_odds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    game_id BIGINT REFERENCES games(game_id),
    event_id TEXT,
    market TEXT NOT NULL,
    entity_type TEXT CHECK(entity_type IN ('batter', 'pitcher', 'team', 'game')),
    player_id BIGINT,
    team_id TEXT,
    opponent_team_id TEXT,
    team_abbr TEXT,
    opponent_team_abbr TEXT,
    selection_key TEXT,
    side TEXT CHECK(side IN ('OVER', 'UNDER', 'YES', 'NO', 'HOME', 'AWAY')),
    bet_type TEXT NOT NULL,
    line DOUBLE PRECISION,
    price_american INTEGER,
    price_decimal DOUBLE PRECISION,
    implied_probability DOUBLE PRECISION,
    odds_decimal DOUBLE PRECISION,
    sportsbook TEXT NOT NULL,
    source_market_key TEXT,
    is_best_available SMALLINT NOT NULL DEFAULT 0 CHECK(is_best_available IN (0, 1)),
    fetched_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_market_odds_lookup
ON market_odds(market, game_id, player_id, team_abbr, bet_type, fetched_at);
CREATE INDEX IF NOT EXISTS idx_market_odds_date_market ON market_odds(game_date, market);
CREATE INDEX IF NOT EXISTS idx_market_odds_game_market ON market_odds(game_id, market);
CREATE INDEX IF NOT EXISTS idx_market_odds_fetched_at ON market_odds(fetched_at);
CREATE INDEX IF NOT EXISTS idx_market_odds_player_id ON market_odds(player_id);
CREATE INDEX IF NOT EXISTS idx_market_odds_team_id ON market_odds(team_id);
CREATE INDEX IF NOT EXISTS idx_market_odds_selection_key ON market_odds(selection_key);

CREATE TABLE IF NOT EXISTS market_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    event_id TEXT,
    market TEXT NOT NULL,
    game_id BIGINT REFERENCES games(game_id),
    entity_type TEXT CHECK(entity_type IN ('batter', 'pitcher', 'team', 'game')),
    player_id BIGINT,
    team_id TEXT,
    opponent_team_id TEXT,
    team_abbr TEXT,
    selection_key TEXT,
    side TEXT CHECK(side IN ('OVER', 'UNDER', 'YES', 'NO', 'HOME', 'AWAY')),
    bet_type TEXT NOT NULL,
    line DOUBLE PRECISION,
    outcome_value DOUBLE PRECISION,
    outcome_text TEXT,
    settled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(market, game_id, player_id, team_abbr, bet_type, line, selection_key)
);

CREATE INDEX IF NOT EXISTS idx_market_outcomes_date_market ON market_outcomes(game_date, market);
CREATE INDEX IF NOT EXISTS idx_market_outcomes_game_market ON market_outcomes(game_id, market);
CREATE INDEX IF NOT EXISTS idx_market_outcomes_player_id ON market_outcomes(player_id);
CREATE INDEX IF NOT EXISTS idx_market_outcomes_team_id ON market_outcomes(team_id);

CREATE TABLE IF NOT EXISTS model_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_run_id BIGINT REFERENCES score_runs(id),
    market TEXT NOT NULL,
    game_id BIGINT NOT NULL REFERENCES games(game_id),
    game_date DATE NOT NULL,
    event_id TEXT,
    entity_type TEXT CHECK(entity_type IN ('batter', 'pitcher', 'team', 'game')),
    player_id BIGINT,
    player_name TEXT,
    team_id TEXT,
    opponent_team_id TEXT,
    team_abbr TEXT,
    opponent_team_abbr TEXT,
    selection_key TEXT,
    side TEXT CHECK(side IN ('OVER', 'UNDER', 'YES', 'NO', 'HOME', 'AWAY')),
    bet_type TEXT NOT NULL,
    line DOUBLE PRECISION,
    model_score DOUBLE PRECISION NOT NULL,
    model_prob DOUBLE PRECISION,
    model_projection DOUBLE PRECISION,
    book_implied_prob DOUBLE PRECISION,
    edge DOUBLE PRECISION,
    signal TEXT CHECK(signal IN ('BET', 'LEAN', 'SKIP', 'FADE')),
    confidence_band TEXT CHECK(confidence_band IN ('HIGH', 'MEDIUM', 'LOW')),
    factors_json TEXT,
    reasons_json TEXT,
    risk_flags_json TEXT,
    lineup_confirmed SMALLINT CHECK(lineup_confirmed IN (0, 1)),
    weather_final SMALLINT CHECK(weather_final IN (0, 1)),
    is_active SMALLINT NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(market, game_id, player_id, team_abbr, bet_type, line, score_run_id)
);

CREATE INDEX IF NOT EXISTS idx_model_scores_date_market
ON model_scores(game_date, market, signal, model_score);
CREATE INDEX IF NOT EXISTS idx_model_scores_game_market ON model_scores(game_id, market);
CREATE INDEX IF NOT EXISTS idx_model_scores_player_id ON model_scores(player_id);
CREATE INDEX IF NOT EXISTS idx_model_scores_team_id ON model_scores(team_id);

CREATE TABLE IF NOT EXISTS bets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT REFERENCES games(game_id),
    game_date DATE NOT NULL,
    market TEXT DEFAULT 'HR',
    player_id BIGINT,
    player_name TEXT,
    team_id TEXT,
    opponent_team_id TEXT,
    selection_key TEXT,
    side TEXT CHECK(side IN ('OVER', 'UNDER', 'YES', 'NO', 'HOME', 'AWAY')),
    bet_type TEXT DEFAULT 'hr_yes',
    line DOUBLE PRECISION,
    sportsbook TEXT,
    odds INTEGER,
    odds_close INTEGER,
    implied_prob_open DOUBLE PRECISION,
    implied_prob_close DOUBLE PRECISION,
    clv_open_to_close DOUBLE PRECISION,
    line_delta DOUBLE PRECISION,
    stake DOUBLE PRECISION,
    units DOUBLE PRECISION,
    model_score DOUBLE PRECISION,
    model_edge DOUBLE PRECISION,
    result TEXT CHECK(result IN ('win', 'loss', 'push', 'void', 'pending')),
    payout DOUBLE PRECISION,
    profit DOUBLE PRECISION,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    settled_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_bets_date ON bets(game_date);
CREATE INDEX IF NOT EXISTS idx_bets_result ON bets(result);
CREATE INDEX IF NOT EXISTS idx_bets_date_market ON bets(game_date, market);
CREATE INDEX IF NOT EXISTS idx_bets_game_market ON bets(game_id, market);
CREATE INDEX IF NOT EXISTS idx_bets_player_id ON bets(player_id);
CREATE INDEX IF NOT EXISTS idx_bets_team_id ON bets(team_id);

CREATE TABLE IF NOT EXISTS closing_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    market TEXT NOT NULL,
    game_id BIGINT NOT NULL,
    event_id TEXT,
    entity_type TEXT,
    player_id BIGINT,
    team_id TEXT,
    opponent_team_id TEXT,
    team_abbr TEXT,
    opponent_team_abbr TEXT,
    selection_key TEXT,
    side TEXT,
    bet_type TEXT,
    line DOUBLE PRECISION,
    sportsbook TEXT,
    price_american INTEGER,
    price_decimal DOUBLE PRECISION,
    implied_probability DOUBLE PRECISION,
    fetched_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(market, game_id, player_id, team_id, selection_key, side, bet_type, line)
);

CREATE INDEX IF NOT EXISTS idx_closing_lines_date_market ON closing_lines(game_date, market);
CREATE INDEX IF NOT EXISTS idx_closing_lines_selection_key ON closing_lines(selection_key);
