/**
 * Demo / fallback data used when Supabase credentials are not configured.
 * Lets the dashboard render a realistic preview for local dev and demos.
 */
export const DEMO = {
  picks: [
    {
      id: 1,
      game_date: "2026-03-27",
      market: "HR",
      sportsbook: "DraftKings",
      game_time: "19:10 ET",
      matchup: "NYY @ BOS",
      team: "NYY",
      player: "Aaron Judge",
      side: "Over",
      line: 0.5,
      odds: "+260",
      model_probability: 0.29,
      implied_probability: 0.22,
      edge_pct: 0.07,
      model_score: 82,
      signal: "BET",
      confidence_band: "HIGH",
      lineup_confirmed: true,
      weather_flag: "OK",
      visibility_tier: "FREE",
      reasons: ["Barrel trend up 14d", "Favorable pull-side wind"],
      risk: ["High-variance market"],
      context: "62\u00b0F, 8mph out to LF; batting order 2",
      factors: { power: 92, park: 70, pitcher_vuln: 81, recent_form: 75 },
    },
    {
      id: 2,
      game_date: "2026-03-27",
      market: "K",
      sportsbook: "FanDuel",
      game_time: "20:05 ET",
      matchup: "SEA @ HOU",
      team: "SEA",
      player: "Luis Castillo",
      side: "Over",
      line: 6.5,
      odds: "-108",
      model_probability: 0.58,
      implied_probability: 0.52,
      edge_pct: 0.06,
      model_score: 76,
      signal: "BET",
      confidence_band: "MEDIUM",
      lineup_confirmed: false,
      weather_flag: "DOME",
      visibility_tier: "PRO",
      reasons: ["Opponent top-5 K% vs RHP", "Pitch count trend stable"],
      risk: ["Lineup not confirmed"],
      context: "Retractable roof",
      factors: { whiff: 88, chase: 81, pitch_count: 72, matchup: 70 },
    },
    {
      id: 3,
      game_date: "2026-03-27",
      market: "ML",
      sportsbook: "DraftKings",
      game_time: "19:40 ET",
      matchup: "LAD @ SF",
      team: "LAD",
      player: "LAD",
      side: "AWAY",
      line: null,
      odds: "-124",
      model_probability: 0.6,
      implied_probability: 0.55,
      edge_pct: 0.05,
      model_score: 74,
      signal: "LEAN",
      confidence_band: "MEDIUM",
      lineup_confirmed: true,
      weather_flag: "OK",
      visibility_tier: "FREE",
      reasons: ["Bullpen edge", "Starter form"],
      risk: ["Road favorite variance"],
      context: "Marine layer",
      factors: { starting_pitch: 80, bullpen: 84, offense: 71 },
    },
  ],

  performance: {
    roi: 8.4,
    winRate: 56.2,
    units: 42.1,
    bets: 318,
    signal: [
      { name: "BET", bets: 134, win: 58.2, roi: 11.3 },
      { name: "LEAN", bets: 144, win: 54.1, roi: 5.2 },
      { name: "FADE", bets: 40, win: 52.0, roi: 2.1 },
    ],
    buckets: [
      { label: "80-89", bets: 52, roi: 14.0 },
      { label: "70-79", bets: 101, roi: 7.8 },
      { label: "60-69", bets: 132, roi: 3.4 },
    ],
  },

  health: {
    stale_sources: ["weather > 90m old"],
    missing_sources: ["umpire feed intermittent"],
    calibration: [
      ["0.55-0.60", 57, 55],
      ["0.60-0.65", 62, 61],
      ["0.65-0.70", 67, 65],
    ],
    factors: [
      ["power", 0.32],
      ["matchup", 0.24],
      ["park", 0.19],
      ["lineup", 0.14],
    ],
  },

  clv: {
    avg: 0.014,
    by: [
      ["HR", "DraftKings", 0.021, 72],
      ["K", "FanDuel", 0.009, 65],
      ["ML", "DraftKings", 0.012, 54],
    ],
  },

  bankroll: {
    current: 642.4,
    peak: 688.1,
    drawdown: -8.6,
    streak: "W3",
    bets: [
      ["2026-03-26", "HR", "Judge O0.5", "+260", 1, "win", 2.6],
      ["2026-03-26", "K", "Castillo O6.5", "-108", 1, "loss", -1.0],
      ["2026-03-25", "ML", "LAD ML", "-124", 1.2, "win", 0.97],
    ],
  },
};
