-- Phase 1A foundation migration (PostgreSQL / Supabase).
-- Idempotent and append-safe for existing installations.

-- ============================================================
-- SCORE RUN AUDIT
-- ============================================================
CREATE TABLE IF NOT EXISTS mlb_score_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_type TEXT NOT NULL,
    game_date DATE,
    market TEXT,
    triggered_by TEXT NOT NULL DEFAULT 'system',
    status TEXT NOT NULL DEFAULT 'started',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    rows_scored INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mlb_score_runs_date_market ON mlb_score_runs(game_date, market);
CREATE INDEX IF NOT EXISTS idx_mlb_score_runs_type_status ON mlb_score_runs(run_type, status);
CREATE INDEX IF NOT EXISTS idx_mlb_score_runs_started_at ON mlb_score_runs(started_at);

-- ============================================================
-- LINEUPS SNAPSHOTS
-- ============================================================
CREATE TABLE IF NOT EXISTS mlb_lineups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    game_id BIGINT NOT NULL,
    team_id TEXT NOT NULL,
    player_id BIGINT NOT NULL,
    batting_order INTEGER,
    position TEXT,
    is_starter SMALLINT NOT NULL DEFAULT 0,
    confirmed SMALLINT NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'mlb_stats_api',
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    active_version SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(
        game_date,
        game_id,
        team_id,
        player_id,
        batting_order,
        position,
        is_starter,
        confirmed,
        fetched_at
    )
);

CREATE INDEX IF NOT EXISTS idx_mlb_lineups_game_date ON mlb_lineups(game_date);
CREATE INDEX IF NOT EXISTS idx_mlb_lineups_game_id ON mlb_lineups(game_id);
CREATE INDEX IF NOT EXISTS idx_mlb_lineups_team_id ON mlb_lineups(team_id);
CREATE INDEX IF NOT EXISTS idx_mlb_lineups_player_id ON mlb_lineups(player_id);
CREATE INDEX IF NOT EXISTS idx_mlb_lineups_fetched_at ON mlb_lineups(fetched_at);
CREATE INDEX IF NOT EXISTS idx_mlb_lineups_active_version ON mlb_lineups(active_version);

-- ============================================================
-- FEATURE STORE TABLES
-- ============================================================
CREATE TABLE IF NOT EXISTS mlb_batter_daily_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    player_id BIGINT NOT NULL,
    team_id TEXT,
    bats TEXT,
    pa_7 INTEGER,
    pa_14 INTEGER,
    pa_30 INTEGER,
    k_pct_7 DOUBLE PRECISION,
    k_pct_14 DOUBLE PRECISION,
    k_pct_30 DOUBLE PRECISION,
    bb_pct_7 DOUBLE PRECISION,
    bb_pct_14 DOUBLE PRECISION,
    bb_pct_30 DOUBLE PRECISION,
    barrel_pct_7 DOUBLE PRECISION,
    barrel_pct_14 DOUBLE PRECISION,
    barrel_pct_30 DOUBLE PRECISION,
    hard_hit_pct_7 DOUBLE PRECISION,
    hard_hit_pct_14 DOUBLE PRECISION,
    hard_hit_pct_30 DOUBLE PRECISION,
    avg_exit_velo_7 DOUBLE PRECISION,
    avg_exit_velo_14 DOUBLE PRECISION,
    avg_exit_velo_30 DOUBLE PRECISION,
    fly_ball_pct_7 DOUBLE PRECISION,
    fly_ball_pct_14 DOUBLE PRECISION,
    fly_ball_pct_30 DOUBLE PRECISION,
    line_drive_pct_7 DOUBLE PRECISION,
    line_drive_pct_14 DOUBLE PRECISION,
    line_drive_pct_30 DOUBLE PRECISION,
    gb_pct_7 DOUBLE PRECISION,
    gb_pct_14 DOUBLE PRECISION,
    gb_pct_30 DOUBLE PRECISION,
    pull_pct_7 DOUBLE PRECISION,
    pull_pct_14 DOUBLE PRECISION,
    pull_pct_30 DOUBLE PRECISION,
    sweet_spot_pct_7 DOUBLE PRECISION,
    sweet_spot_pct_14 DOUBLE PRECISION,
    sweet_spot_pct_30 DOUBLE PRECISION,
    avg_launch_angle_7 DOUBLE PRECISION,
    avg_launch_angle_14 DOUBLE PRECISION,
    avg_launch_angle_30 DOUBLE PRECISION,
    iso_7 DOUBLE PRECISION,
    iso_14 DOUBLE PRECISION,
    iso_30 DOUBLE PRECISION,
    slg_7 DOUBLE PRECISION,
    slg_14 DOUBLE PRECISION,
    slg_30 DOUBLE PRECISION,
    ba_7 DOUBLE PRECISION,
    ba_14 DOUBLE PRECISION,
    ba_30 DOUBLE PRECISION,
    hit_rate_7 DOUBLE PRECISION,
    hit_rate_14 DOUBLE PRECISION,
    hit_rate_30 DOUBLE PRECISION,
    tb_per_pa_7 DOUBLE PRECISION,
    tb_per_pa_14 DOUBLE PRECISION,
    tb_per_pa_30 DOUBLE PRECISION,
    hr_rate_7 DOUBLE PRECISION,
    hr_rate_14 DOUBLE PRECISION,
    hr_rate_30 DOUBLE PRECISION,
    singles_rate_14 DOUBLE PRECISION,
    singles_rate_30 DOUBLE PRECISION,
    doubles_rate_14 DOUBLE PRECISION,
    doubles_rate_30 DOUBLE PRECISION,
    triples_rate_14 DOUBLE PRECISION,
    triples_rate_30 DOUBLE PRECISION,
    rbi_rate_14 DOUBLE PRECISION,
    rbi_rate_30 DOUBLE PRECISION,
    runs_rate_14 DOUBLE PRECISION,
    runs_rate_30 DOUBLE PRECISION,
    walk_rate_14 DOUBLE PRECISION,
    walk_rate_30 DOUBLE PRECISION,
    iso_vs_lhp DOUBLE PRECISION,
    iso_vs_rhp DOUBLE PRECISION,
    hit_rate_vs_lhp DOUBLE PRECISION,
    hit_rate_vs_rhp DOUBLE PRECISION,
    k_pct_vs_lhp DOUBLE PRECISION,
    k_pct_vs_rhp DOUBLE PRECISION,
    hot_cold_delta_iso DOUBLE PRECISION,
    hot_cold_delta_hit_rate DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, player_id)
);

CREATE INDEX IF NOT EXISTS idx_mlb_batter_daily_features_game_date ON mlb_batter_daily_features(game_date);
CREATE INDEX IF NOT EXISTS idx_mlb_batter_daily_features_player_id ON mlb_batter_daily_features(player_id);
CREATE INDEX IF NOT EXISTS idx_mlb_batter_daily_features_team_id ON mlb_batter_daily_features(team_id);

CREATE TABLE IF NOT EXISTS mlb_pitcher_daily_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    pitcher_id BIGINT NOT NULL,
    team_id TEXT,
    throws TEXT,
    batters_faced_14 INTEGER,
    batters_faced_30 INTEGER,
    k_pct_14 DOUBLE PRECISION,
    k_pct_30 DOUBLE PRECISION,
    bb_pct_14 DOUBLE PRECISION,
    bb_pct_30 DOUBLE PRECISION,
    hr_per_9_14 DOUBLE PRECISION,
    hr_per_9_30 DOUBLE PRECISION,
    hr_per_fb_14 DOUBLE PRECISION,
    hr_per_fb_30 DOUBLE PRECISION,
    hard_hit_pct_allowed_14 DOUBLE PRECISION,
    hard_hit_pct_allowed_30 DOUBLE PRECISION,
    barrel_pct_allowed_14 DOUBLE PRECISION,
    barrel_pct_allowed_30 DOUBLE PRECISION,
    avg_exit_velo_allowed_14 DOUBLE PRECISION,
    avg_exit_velo_allowed_30 DOUBLE PRECISION,
    fly_ball_pct_allowed_14 DOUBLE PRECISION,
    fly_ball_pct_allowed_30 DOUBLE PRECISION,
    whiff_pct_14 DOUBLE PRECISION,
    whiff_pct_30 DOUBLE PRECISION,
    chase_pct_14 DOUBLE PRECISION,
    chase_pct_30 DOUBLE PRECISION,
    avg_fastball_velo_14 DOUBLE PRECISION,
    avg_fastball_velo_30 DOUBLE PRECISION,
    fastball_velo_trend_14 DOUBLE PRECISION,
    outs_recorded_avg_last_5 DOUBLE PRECISION,
    pitches_avg_last_5 DOUBLE PRECISION,
    starter_role_confidence DOUBLE PRECISION,
    split_k_pct_vs_lhh DOUBLE PRECISION,
    split_k_pct_vs_rhh DOUBLE PRECISION,
    split_hr_allowed_rate_vs_lhh DOUBLE PRECISION,
    split_hr_allowed_rate_vs_rhh DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, pitcher_id)
);

CREATE INDEX IF NOT EXISTS idx_mlb_pitcher_daily_features_game_date ON mlb_pitcher_daily_features(game_date);
CREATE INDEX IF NOT EXISTS idx_mlb_pitcher_daily_features_pitcher_id ON mlb_pitcher_daily_features(pitcher_id);
CREATE INDEX IF NOT EXISTS idx_mlb_pitcher_daily_features_team_id ON mlb_pitcher_daily_features(team_id);

CREATE TABLE IF NOT EXISTS mlb_team_daily_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    team_id TEXT NOT NULL,
    opponent_team_id TEXT,
    offense_k_pct_14 DOUBLE PRECISION,
    offense_k_pct_30 DOUBLE PRECISION,
    offense_bb_pct_14 DOUBLE PRECISION,
    offense_bb_pct_30 DOUBLE PRECISION,
    offense_iso_14 DOUBLE PRECISION,
    offense_iso_30 DOUBLE PRECISION,
    offense_ba_14 DOUBLE PRECISION,
    offense_ba_30 DOUBLE PRECISION,
    offense_obp_14 DOUBLE PRECISION,
    offense_obp_30 DOUBLE PRECISION,
    offense_slg_14 DOUBLE PRECISION,
    offense_slg_30 DOUBLE PRECISION,
    offense_hit_rate_14 DOUBLE PRECISION,
    offense_hit_rate_30 DOUBLE PRECISION,
    offense_tb_per_pa_14 DOUBLE PRECISION,
    offense_tb_per_pa_30 DOUBLE PRECISION,
    runs_per_game_14 DOUBLE PRECISION,
    runs_per_game_30 DOUBLE PRECISION,
    hr_rate_14 DOUBLE PRECISION,
    hr_rate_30 DOUBLE PRECISION,
    bullpen_era_proxy_14 DOUBLE PRECISION,
    bullpen_whip_proxy_14 DOUBLE PRECISION,
    bullpen_k_pct_14 DOUBLE PRECISION,
    bullpen_hr9_14 DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, team_id)
);

CREATE INDEX IF NOT EXISTS idx_mlb_team_daily_features_game_date ON mlb_team_daily_features(game_date);
CREATE INDEX IF NOT EXISTS idx_mlb_team_daily_features_team_id ON mlb_team_daily_features(team_id);
CREATE INDEX IF NOT EXISTS idx_mlb_team_daily_features_opp_team_id ON mlb_team_daily_features(opponent_team_id);

CREATE TABLE IF NOT EXISTS mlb_game_context_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL,
    game_id BIGINT NOT NULL,
    home_team_id TEXT NOT NULL,
    away_team_id TEXT NOT NULL,
    home_pitcher_id BIGINT,
    away_pitcher_id BIGINT,
    park_factor_hr DOUBLE PRECISION,
    park_factor_runs DOUBLE PRECISION,
    park_factor_hits DOUBLE PRECISION,
    weather_temp_f DOUBLE PRECISION,
    weather_wind_speed_mph DOUBLE PRECISION,
    weather_wind_dir TEXT,
    weather_hr_multiplier DOUBLE PRECISION,
    weather_run_multiplier DOUBLE PRECISION,
    umpire_name TEXT,
    umpire_k_boost DOUBLE PRECISION,
    umpire_run_env DOUBLE PRECISION,
    lineups_confirmed_home SMALLINT NOT NULL DEFAULT 0,
    lineups_confirmed_away SMALLINT NOT NULL DEFAULT 0,
    is_final_context SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(game_date, game_id)
);

CREATE INDEX IF NOT EXISTS idx_mlb_game_context_features_game_date ON mlb_game_context_features(game_date);
CREATE INDEX IF NOT EXISTS idx_mlb_game_context_features_game_id ON mlb_game_context_features(game_id);
CREATE INDEX IF NOT EXISTS idx_mlb_game_context_features_home_team ON mlb_game_context_features(home_team_id);
CREATE INDEX IF NOT EXISTS idx_mlb_game_context_features_away_team ON mlb_game_context_features(away_team_id);

-- Backfill columns that older mlb_pitcher_stats installs may not have.
ALTER TABLE mlb_pitcher_stats ADD COLUMN IF NOT EXISTS batters_faced INTEGER;
ALTER TABLE mlb_pitcher_stats ADD COLUMN IF NOT EXISTS k_pct DOUBLE PRECISION;
ALTER TABLE mlb_pitcher_stats ADD COLUMN IF NOT EXISTS bb_pct DOUBLE PRECISION;
ALTER TABLE mlb_pitcher_stats ADD COLUMN IF NOT EXISTS so_per_9 DOUBLE PRECISION;
ALTER TABLE mlb_pitcher_stats ADD COLUMN IF NOT EXISTS k_pct_vs_lhb DOUBLE PRECISION;
ALTER TABLE mlb_pitcher_stats ADD COLUMN IF NOT EXISTS k_pct_vs_rhb DOUBLE PRECISION;

-- ============================================================
-- GENERIC TABLE SHAPE HARDENING
-- ============================================================
CREATE TABLE IF NOT EXISTS mlb_market_odds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market TEXT NOT NULL,
    game_id BIGINT,
    player_id BIGINT,
    team_abbr TEXT,
    opponent_team_abbr TEXT,
    bet_type TEXT NOT NULL,
    line DOUBLE PRECISION,
    odds_decimal DOUBLE PRECISION,
    sportsbook TEXT NOT NULL,
    fetched_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mlb_market_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market TEXT NOT NULL,
    game_id BIGINT,
    player_id BIGINT,
    team_abbr TEXT,
    bet_type TEXT NOT NULL,
    line DOUBLE PRECISION,
    outcome_value DOUBLE PRECISION,
    outcome_text TEXT,
    settled_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS mlb_model_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market TEXT NOT NULL,
    game_id BIGINT NOT NULL,
    game_date DATE NOT NULL,
    player_id BIGINT,
    player_name TEXT,
    team_abbr TEXT,
    opponent_team_abbr TEXT,
    bet_type TEXT NOT NULL,
    line DOUBLE PRECISION,
    model_score DOUBLE PRECISION NOT NULL,
    model_prob DOUBLE PRECISION,
    model_projection DOUBLE PRECISION,
    book_implied_prob DOUBLE PRECISION,
    edge DOUBLE PRECISION,
    signal TEXT,
    factors_json TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mlb_bets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT,
    game_date DATE NOT NULL,
    player_id BIGINT,
    player_name TEXT,
    bet_type TEXT DEFAULT 'hr_yes',
    sportsbook TEXT,
    odds INTEGER,
    stake DOUBLE PRECISION,
    units DOUBLE PRECISION,
    model_score DOUBLE PRECISION,
    model_edge DOUBLE PRECISION,
    result TEXT,
    payout DOUBLE PRECISION,
    profit DOUBLE PRECISION,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    settled_at TIMESTAMPTZ
);

ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS game_date DATE;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS event_id TEXT;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS team_id TEXT;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS opponent_team_id TEXT;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS selection_key TEXT;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS side TEXT;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS price_american INTEGER;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS price_decimal DOUBLE PRECISION;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS implied_probability DOUBLE PRECISION;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS source_market_key TEXT;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS is_best_available SMALLINT DEFAULT 0;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE mlb_market_odds ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS game_date DATE;
ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS event_id TEXT;
ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS team_id TEXT;
ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS opponent_team_id TEXT;
ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS selection_key TEXT;
ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS side TEXT;
ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE mlb_market_outcomes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS score_run_id BIGINT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS event_id TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS team_id TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS opponent_team_id TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS selection_key TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS side TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS confidence_band TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS reasons_json TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS risk_flags_json TEXT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS lineup_confirmed SMALLINT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS weather_final SMALLINT;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS is_active SMALLINT DEFAULT 1;
ALTER TABLE mlb_model_scores ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS market TEXT DEFAULT 'HR';
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS team_id TEXT;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS opponent_team_id TEXT;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS selection_key TEXT;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS side TEXT;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS line DOUBLE PRECISION;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS odds_close INTEGER;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS implied_prob_open DOUBLE PRECISION;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS implied_prob_close DOUBLE PRECISION;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS clv_open_to_close DOUBLE PRECISION;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS line_delta DOUBLE PRECISION;
ALTER TABLE mlb_bets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_mlb_market_odds_date_market ON mlb_market_odds(game_date, market);
CREATE INDEX IF NOT EXISTS idx_mlb_market_odds_game_market ON mlb_market_odds(game_id, market);
CREATE INDEX IF NOT EXISTS idx_mlb_market_odds_fetched_at ON mlb_market_odds(fetched_at);
CREATE INDEX IF NOT EXISTS idx_mlb_market_odds_player_id ON mlb_market_odds(player_id);
CREATE INDEX IF NOT EXISTS idx_mlb_market_odds_team_id ON mlb_market_odds(team_id);

CREATE INDEX IF NOT EXISTS idx_mlb_market_outcomes_date_market ON mlb_market_outcomes(game_date, market);
CREATE INDEX IF NOT EXISTS idx_mlb_market_outcomes_game_market ON mlb_market_outcomes(game_id, market);
CREATE INDEX IF NOT EXISTS idx_mlb_market_outcomes_player_id ON mlb_market_outcomes(player_id);
CREATE INDEX IF NOT EXISTS idx_mlb_market_outcomes_team_id ON mlb_market_outcomes(team_id);

CREATE INDEX IF NOT EXISTS idx_mlb_model_scores_game_market ON mlb_model_scores(game_id, market);
CREATE INDEX IF NOT EXISTS idx_mlb_model_scores_player_id ON mlb_model_scores(player_id);
CREATE INDEX IF NOT EXISTS idx_mlb_model_scores_team_id ON mlb_model_scores(team_id);

CREATE INDEX IF NOT EXISTS idx_mlb_bets_date_market ON mlb_bets(game_date, market);
CREATE INDEX IF NOT EXISTS idx_mlb_bets_game_market ON mlb_bets(game_id, market);
CREATE INDEX IF NOT EXISTS idx_mlb_bets_player_id ON mlb_bets(player_id);
CREATE INDEX IF NOT EXISTS idx_mlb_bets_team_id ON mlb_bets(team_id);
