-- Phase 6: mlb_daily_cards table
-- Materialized daily card built from mlb_model_scores signals.

CREATE TABLE IF NOT EXISTS mlb_daily_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_date DATE NOT NULL UNIQUE,
    card_data JSONB NOT NULL DEFAULT '[]',
    top_plays JSONB NOT NULL DEFAULT '[]',
    summary TEXT,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mlb_daily_cards_game_date ON mlb_daily_cards(game_date);
CREATE INDEX IF NOT EXISTS idx_mlb_daily_cards_published ON mlb_daily_cards(published, game_date);
